### ISSUE TITLE
대화 중단한 것 / 중단된 것 소프트 삭제

### ISSUE THREAD

**Issue by injoon2019** [Nexters/Bottles_BE#171]
## ✔️ To-Do
대화 중단한 것 / 중단된 것 3일 뒤 소프트 삭제

**Comment by miseongk** [comment]
- 대화 '중단' 된 보틀은 -> "완료"하기 탭으로 이동, 3일 후 리스트에서 사라짐으로 결정

위 변경사항 반영하기
