### ISSUE TITLE
이미지 블러처리 서버에서 하도록 복구

### ISSUE THREAD

**Issue by injoon2019** [Nexters/Bottles_BE#421]
## 💬 설명
- 프론트에서 원형에 맞게 블러처리 하는 것이 힘들고 (현재는 이미지 원을 포함한 사각형이 블러처리)
- 웹뷰에서 사진을 꾹 누르면 사진이 보이는 문제가 있어, 서버에서 하도록 복구합니다

## ✔️ To-Do
이미지 블러처리 서버에서 하도록 복구

**Comment by injoon2019** [comment]
https://github.com/Nexters/Bottles_BE/pull/326

**Comment by miseongk** [comment]
#444
